Repository JoomlaPolska/jezyk-J4, pull requests merged in 2024-07, with the labels that each got.

#528 Środowisko docker-a do testowania instalacji tłumaczenia
  .docs/testing.md
  README.md
  docker-compose.yml
Labels: documentation, enhancement

#537 Update com_content.ini
  administrator/language/pl-PL/com_content.ini
Labels: bug

#541 Update com_content.ini
  administrator/language/pl-PL/com_content.ini
Labels: bug, Joomla! 5.1

#542 Update plg_editors_tinymce.ini
  administrator/language/pl-PL/plg_editors_tinymce.ini
Labels: enhancement, Joomla! 5.1

#540 Poprawa tłumaczenia opisu opcji Korespondencji masowej w konfiguracji globalnej
  administrator/language/pl-PL/com_config.ini
Labels: Joomla! 5.1

#543 Poprawa tłumaczenia komponentu Aktualizacja Joomla!
  administrator/language/pl-PL/com_joomlaupdate.ini
Labels: enhancement
